<a href="https://colab.research.google.com/github/leeet1004835/colab/blob/main/0416_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
print(np.__version__) # 屬性檢查版本號
print(np.__file__) #  屬性檢查安裝路徑

2.0.2
/usr/local/lib/python3.12/dist-packages/numpy/__init__.py


In [10]:
# 從list創造ndarray
prime_list = [2, 3, 5, 7, 11]
print(prime_list)
print(type(prime_list))

prime_array = np.array(prime_list)
print(prime_array)
print(type(prime_array))

[2, 3, 5, 7, 11]
<class 'list'>
[ 2  3  5  7 11]
<class 'numpy.ndarray'>


In [13]:
print(prime_list + prime_list)
print(prime_list * 3)

print(prime_array + prime_array)
print(prime_array * 3)

[2, 3, 5, 7, 11, 2, 3, 5, 7, 11]
[2, 3, 5, 7, 11, 2, 3, 5, 7, 11, 2, 3, 5, 7, 11]
[ 4  6 10 14 22]
[ 6  9 15 21 33]


In [ ]:
print(np.zeros(5, dtype = int))