<a href="https://colab.research.google.com/github/leeet1004835/colab/blob/main/0416_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
print(np.__version__) # 屬性檢查版本號
print(np.__file__) #  屬性檢查安裝路徑

2.0.2
/usr/local/lib/python3.12/dist-packages/numpy/__init__.py


In [10]:
# 從 list 創造 ndarray
prime_list = [2, 3, 5, 7, 11]
print(prime_list)
print(type(prime_list))

prime_array = np.array(prime_list)
print(prime_array)
print(type(prime_array))

[2, 3, 5, 7, 11]
<class 'list'>
[ 2  3  5  7 11]
<class 'numpy.ndarray'>


In [14]:
print(prime_list + prime_list) # concatenation
print(prime_list * 3) # duplicate/extend

print(prime_array + prime_array) # element-wise add
print(prime_array * 3) # element-wise multiply
print(prime_array ** 2) # element-wise power

[2, 3, 5, 7, 11, 2, 3, 5, 7, 11]
[2, 3, 5, 7, 11, 2, 3, 5, 7, 11, 2, 3, 5, 7, 11]
[ 4  6 10 14 22]
[ 6  9 15 21 33]
[  4   9  25  49 121]


In [20]:
'''
利用 NumPy 函數創造內容元素相同的 ndarray
np.zeros()
np.ones()
np.full()
'''
print(np.zeros(5, dtype = int)) # dtype = data type
print(np.ones(5, dtype = int))
print(np.ones(10, dtype = int) * 5566)
print(np.full(10, 5566, dtype = int))

[0 0 0 0 0]
[1 1 1 1 1]
[5566 5566 5566 5566 5566 5566 5566 5566 5566 5566]
[5566 5566 5566 5566 5566 5566 5566 5566 5566 5566]


In [28]:
'''
利用 NumPy 函數創造數列型態的 ndarray
np.arange(start, stop, step)
np.linspace(start, stop, num)值得注意的是stop參數預設為包含。
'''
print(np.arange(1, 11, 2))
print(np.linspace(1, 100, 10, dtype = int)) # 固定間距的數列

[1 3 5 7 9]
[  1  12  23  34  45  56  67  78  89 100]


In [37]:
# 可內積(dot)的
# (m, n) dot (i, j), n == i
arr_1 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
arr_2 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
print(arr_1.shape)
print(arr_2.T.shape)
np.dot(arr_1, arr_2.T)
print(len(arr_1.shape))
print(arr_1.ndim)

(3, 2)
(2, 3)
2
2


In [38]:
'''
常用的 ndarray 屬性:
ndarray.ndim 維度數。
ndarray.shape 外型。
ndarray.size 元素個數。
ndarray.dtype 資料類別。
'''
prime_list = [2, 3, 5, 7, 11]
prime_array = np.array(prime_list)
print(prime_array)
print(prime_array.ndim)
print(prime_array.shape)
print(prime_array.size)
print(prime_array.dtype)

[ 2  3  5  7 11]
1
(5,)
5
int64


In [49]:
'''
零維 ndarray: 純量
一維 ndarray: 向量
二維 ndarray: 矩陣
三維或者n維 ndarray: 張量
'''
an_integer = 5566
print(an_integer)

scalar = np.array(an_integer)
print(scalar)
print(scalar.shape)
print(scalar.ndim)

vector = np.array([5, 5, 6, 6])
print(vector)
print(vector.shape) # 四個元素
print(vector.ndim) # 維度是1

matrix = np.array([
    [5, 5],
    [6, 6]
])
print(matrix)
print(matrix.shape) # 2 rows, 4 columns
print(matrix.ndim) # 維度是2

tensor = np.array([
    [
        [5, 5],
        [6, 6]
    ],
    [
        [5, 5],
        [6, 6]
    ],
    [
        [5, 5],
        [6, 6]
    ]
])
print(tensor)
print(tensor.shape)
print(tensor.ndim) # 維度是3

5566
5566
()
0
[5 5 6 6]
(4,)
1
[[5 5]
 [6 6]]
(2, 2)
2
[[[5 5]
  [6 6]]

 [[5 5]
  [6 6]]

 [[5 5]
  [6 6]]]
(3, 2, 2)
3
