<a href="https://colab.research.google.com/github/leeet1004835/colab/blob/main/0423.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''
資料科學的研究流程(循環、非線性):
資料載入。
資料清理。
資料轉換。
資料視覺化。
模型。
溝通。
'''

'\n資料科學的研究流程(循環、非線性):\n資料載入。\n資料清理。\n資料轉換。\n資料視覺化。\n模型。\n溝通。\n'

In [2]:
'''
機器學習的定義:三個要素、一個但書
[要素]
experience E (訓練資料/歷史資料)
tasks T (目的性)
performance measure P (準確度)
[但書]
if its performance at tasks in T, as measured by P,
improves with experience E.
(它在任務T中的表現(由指標P來衡量)，會隨著經驗E的增加而提升。)
'''

'\n機器學習的定義:三個要素、一個但書\n[要素]\nexperience E (訓練資料/歷史資料)\ntasks T (目的性)\nperformance measure P (準確度)\n[但書]\nif its performance at tasks in T, as measured by P,\nimproves with experience E.\n(它在任務T中的表現(由指標P來衡量)，會隨著經驗E的增加而提升。)\n'

In [3]:
'''
機器學習的模型可在分為:
[監督式學習]:訓練資料中具備以實現的數值或標籤。
迴歸:數值預測的任務。
分類:類別預測的任務。
[非監督式學習]:訓練資料中「不」具備任何的數值或標籤。
'''

'\n機器學習的模型可在分為:\n[監督式學習]:訓練資料中具備以實現的數值或標籤。\n迴歸:數值預測的任務。\n分類:類別預測的任務。\n[非監督式學習]:訓練資料中「不」具備任何的數值或標籤。\n'

In [4]:
'''
模型(Model)是一個類似於「函數」的概念，由參數與運算組成。
模型的參數以及運算可以透過不同的方式生成，生成方式包含規則敘述與歷史資料訓練。
透過規則敘述生成參數以及運算，稱為基於規則模型(Rule-based medel)或稱專家模型。
透過歷史資料訓練生成參數以及運算，稱為基於演算法的模型(Algorithm-based medel)或稱基於機器學習的模型。
基於規則模型:問題能用人類語言描述邏輯、撰寫規則。答案不能容忍誤差。給定整數判斷它是否為奇數、偶數或質數。
基於演算法的模型:問題非領域專家不容易描述邏輯、撰寫規則。答案能夠容忍誤差。給定圖片判斷是貓或狗、給定房屋資訊預測房價。
'''

'\n模型(Model)是一個類似於「函數」的概念，由參數與運算組成。\n模型的參數以及運算可以透過不同的方式生成，生成方式包含規則敘述與歷史資料訓練。\n透過規則敘述生成參數以及運算，稱為基於規則模型(Rule-based medel)或稱專家模型。\n透過歷史資料訓練生成參數以及運算，稱為基於演算法的模型(Algorithm-based medel)或稱基於機器學習的模型。\n基於規則模型:問題能用人類語言描述邏輯、撰寫規則。答案不能容忍誤差。給定整數判斷它是否為奇數、偶數或質數。\n基於演算法的模型:問題非領域專家不容易描述邏輯、撰寫規則。答案能夠容忍誤差。給定圖片判斷是貓或狗、給定房屋資訊預測房價。\n'

In [5]:
'''
關於訓練、驗證與測試:
機器學習專案中的訓練、驗證來自具備已實現數值或標籤資料集。
測試則來自未實現數值或標籤資料集。
在從未見過的測試資料上之表現將決定他是否會被部署到正式環境開始運作。
'''

'\n關於訓練、驗證與測試:\n機器學習專案中的訓練、驗證來自具備已實現數值或標籤資料集。\n測試則來自未實現數值或標籤資料集。\n在從未見過的測試資料上之表現將決定他是否會被部署到正式環境開始運作。\n'

In [6]:
'''
減少訓練誤差的具體做法:
增加梯度遞減的訓練次數。
透過交叉驗證(Cross validation)的技巧消弭訓練與驗證資料切割所造成的誤差。
增加特徵矩陣的欄位。

減少訓練誤差與測試誤差的間距:
引用正規化（Regularization）的技巧。
減少訓練誤差的過程，很有可能伴隨而來的是驗證或測試誤差的升高。
模型對於訓練資料過於熟悉，而降低了它的泛化能力。
這樣的狀態我們稱之為「過度配適」（Overfitting）。
'''

'\n減少訓練誤差的具體做法\n增加梯度遞減的訓練次數。\n透過交叉驗證(Cross validation)的技巧消弭訓練與驗證資料切割所造成的誤差。\n增加特徵矩陣的欄位。\n'

In [ ]:
'''
Scikit-learn 是 Python 機器學習的第三方模組，
透過它可以進行監督式以及非監督式學習，提供了模型訓練、資料預處理、模型選擇以及模型評估等功能。

Scikit-Learn 應用程式介面設計原則:
一致性。
可檢查性。
不擴增新類別。
可組合性。
合理預設參數。
'''

In [ ]:
'''
轉換器與預測器是 Scikit-Learn 所創造最重要的兩種類別:
轉換器:用來預處理資料。
預測器:用來訓練模型、生成規則w。

使用 Scikit-Learn 轉換器的標準步驟:
準備欲轉換的特徵矩陣X或目標陣列y。
建立轉換器類別的物件。
將欲轉換的特徵矩陣X或目標陣列y輸入transformer.fit_transform()。
檢查轉換結果。
'''

In [7]:
# 使用 Scikit-Learn 轉換器 PolynomialFeatures 生成一個指定次方數的特徵多項式矩陣。

import pandas as pd
from sklearn.preprocessing import PolynomialFeatures # 多次多項特徵

csv_url = "https://raw.githubusercontent.com/yaojenkuo/ml-newbies/master/player_stats.csv"
player_stats = pd.read_csv(csv_url)
X = player_stats["heightMeters"].values.reshape(-1, 1) # step 1
polynomial_features = PolynomialFeatures()             # step 2
X_transformed = polynomial_features.fit_transform(X)   # step 3
print(X_transformed[:5])                               # step 4

[[1.     2.03   4.1209]
 [1.     2.11   4.4521]
 [1.     2.06   4.2436]
 [1.     1.9    3.61  ]
 [1.     1.98   3.9204]]


In [8]:
player_stats.head()

,firstName,lastName,temporaryDisplayName,personId,teamId,jersey,isActive,pos,heightFeet,heightInches,...,ftm,fta,pFouls,points,gamesPlayed,gamesStarted,plusMinus,min,dd2,td3
0,Precious,Achiuwa,"Achiuwa, Precious",1630173,1610612748,5.0,True,F,6,8,...,56.0,110.0,91.0,304.0,61.0,4.0,-116.0,737.0,3.0,0.0
1,Steven,Adams,"Adams, Steven",203500,1610612740,12.0,True,C,6,11,...,936.0,1708.0,1497.0,5629.0,588.0,524.0,1638.0,15812.0,125.0,1.0
2,Bam,Adebayo,"Adebayo, Bam",1628389,1610612748,13.0,True,C-F,6,9,...,842.0,1141.0,668.0,3549.0,287.0,183.0,258.0,7840.0,91.0,5.0
3,Ty-Shon,Alexander,"Alexander, Ty-Shon",1630234,1610612756,0.0,True,G,6,3,...,1.0,2.0,2.0,9.0,15.0,0.0,-8.0,47.0,0.0,0.0
4,Nickeil,Alexander-Walker,"Alexander-Walker, Nickeil",1629638,1610612740,6.0,True,G,6,6,...,73.0,103.0,145.0,775.0,93.0,14.0,-105.0,1597.0,0.0,0.0


In [14]:
X = player_stats["heightMeters"].values.reshape(-1, 1)
print(X.shape)
print(X)

(503, 1)
[[2.03]
 [2.11]
 [2.06]
 [1.9 ]
 [1.98]
 [1.93]
 [2.11]
 [2.03]
 [2.06]
 [2.11]
 [2.08]
 [1.98]
 [2.01]
 [1.88]
 [2.01]
 [1.9 ]
 [2.03]
 [1.8 ]
 [2.06]
 [2.11]
 [2.08]
 [1.98]
 [2.11]
 [1.98]
 [1.98]
 [2.13]
 [1.96]
 [2.03]
 [1.98]
 [1.98]
 [2.03]
 [2.03]
 [2.08]
 [1.93]
 [2.03]
 [1.9 ]
 [1.93]
 [2.03]
 [1.96]
 [2.08]
 [1.85]
 [2.01]
 [2.01]
 [2.06]
 [2.11]
 [2.03]
 [2.08]
 [1.85]
 [1.93]
 [1.98]
 [2.01]
 [2.18]
 [2.03]
 [1.96]
 [2.06]
 [1.9 ]
 [2.08]
 [1.96]
 [1.98]
 [1.98]
 [1.98]
 [2.08]
 [2.01]
 [1.96]
 [1.9 ]
 [2.01]
 [1.93]
 [1.98]
 [2.18]
 [1.96]
 [1.98]
 [1.98]
 [1.85]
 [1.96]
 [2.08]
 [1.98]
 [1.83]
 [1.98]
 [2.01]
 [2.01]
 [1.96]
 [1.78]
 [2.03]
 [2.08]
 [2.06]
 [1.85]
 [2.08]
 [1.96]
 [1.93]
 [2.13]
 [1.8 ]
 [1.98]
 [2.03]
 [1.93]
 [2.11]
 [2.01]
 [2.06]
 [2.11]
 [1.85]
 [1.96]
 [2.03]
 [2.08]
 [2.01]
 [2.01]
 [1.98]
 [1.98]
 [1.88]
 [1.9 ]
 [1.98]
 [2.08]
 [2.06]
 [1.93]
 [1.98]
 [2.13]
 [1.9 ]
 [1.98]
 [2.06]
 [1.96]
 [2.08]
 [1.96]
 [1.93]
 [2.01]
 [1.9 ]
 [1.96]

In [15]:
from sklearn.preprocessing import PolynomialFeatures

polynomial_features = PolynomialFeatures() # 合理預設參數(degree = 2)
X_transformed = polynomial_features.fit_transform(X) # [X0,身高公尺,身高公尺的平方]
print(X_transformed.shape)
print(X_transformed)

(503, 3)
[[1.     2.03   4.1209]
 [1.     2.11   4.4521]
 [1.     2.06   4.2436]
 ...
 [1.     2.13   4.5369]
 [1.     2.11   4.4521]
 [1.     2.13   4.5369]]
