<a href="https://colab.research.google.com/github/leeet1004835/colab/blob/main/04_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 臺灣銀行委辦 AI 人才進階訓練

> 隨堂練習：數據分析，2026-04-10

[郭耀仁](https://hahow.in/@tonykuoyj?tr=tonykuoyj) | <yaojenkuo@ntu.edu.tw>

## 練習題指引

- 單選題：覺得第一個選項正確，就將 `None` 改寫為 1，覺得第二個選項正確，就將 `None` 改寫為 2，覺得第三個選項正確，就將 `None` 改寫 3，覺得第四個選項正確，就將 `None` 改寫 4
- 練習題已經給定函數、類別、預期輸入或參數名稱，我們只需要寫作程式區塊。同時也給定函數的類別提示，說明預期輸入以及預期輸出的類別。
- 說明（Docstring）會描述測試如何進行，閱讀說明能夠暸解預期輸入以及預期輸出之間的關係，幫助我們更快解題。
- 請在 `### BEGIN SOLUTION` 與 `### END SOLUTION` 這兩個註解之間寫作函數或者類別的程式區塊。
- 將預期輸出放置在 `return` 保留字之後，若只是用 `print()` 函數將預期輸出印出無法通過測試。
- 語法錯誤（`SyntaxError`）或縮排錯誤（`IndentationError`）等將會導致測試失效，測試之前應該先在筆記本使用函數觀察是否與說明（Docstring）描述的功能相符。
- 執行測試的步驟：
    1. 點選右上角 Connect
    2. 點選上方選單的 Runtime -> Restart and run all -> Yes -> Run anyway
    3. 移動到 Google Colab 的最後一個儲存格看批改測試結果。

## 01. 下列有關 `ndarray` 的別名何者為真？

1. 零維的 `ndarray` 別名為純量（Scalar）。
2. 一維的 `ndarray` 別名為向量（Vector）。
3. 二維的 `ndarray` 別名為矩陣（Matrix）。
4. 三維或更高維度的 `ndarray` 別名為張量（Tensor）。
5. 以上皆是。

In [ ]:
answer_01 = None

## 02. 下列何者不是 `pandas` 模組所設計的資料結構？

1. `Index`
2. `Series`
3. `DataFrame`
4. `ndarray`

In [ ]:
answer_02 = None

## 03. 前十個質數

定義函數 `create_first_ten_primes_array()` 回傳一個外型為 `(10,)`、儲存了前十個質數的 `ndarray`

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
def create_first_ten_primes_array() -> np.ndarray:
    """
    >>> first_ten_primes_array = create_first_ten_primes_array()
    >>> first_ten_primes_array
    array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29])
    >>> type(first_ten_primes_array)
    numpy.ndarray
    >>> first_ten_primes_array.shape
    (10,)
    """
    ### BEGIN SOLUTION

    ### END SOLUTION

## 04. 前十個偶數

定義函數 `create_first_ten_evens_array()` 回傳一個外型為 `(10,)`、儲存了前十個偶數的 `ndarray`

In [ ]:
def create_first_ten_evens_array() -> np.ndarray:
    """
    >>> first_ten_evens_array = create_first_ten_evens_array()
    >>> first_ten_evens_array
    array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
    >>> type(first_ten_evens_array)
    numpy.ndarray
    >>> first_ten_evens_array.shape
    (10,)
    """
    ### BEGIN SOLUTION

    ### END SOLUTION

## 05. 將數個距離由公里轉換英里

定義函數 `convert_kilometers_to_miles()` 能夠將數個單位為公里的距離轉換為英里。

\begin{equation}
1 \; \text{km} = 0.62137 \; \text{mile}
\end{equation}

In [ ]:
def convert_kilometers_to_miles(x: np.ndarray) -> np.ndarray:
    """
    >>> convert_kilometers_to_miles(np.array([1.6, 3, 5, 10, 21.095, 42.195]))
    array([ 0.994192  ,  1.86411   ,  3.10685   ,  6.2137    , 13.10780015,
           26.21870715])
    """
    ### BEGIN SOLUTION

    ### END SOLUTION

## 06. 建立前 5 個整數的 `DataFrame`

定義函數 `create_first_five_integer_dataframe()` 能夠回傳指定的 `DataFrame`

In [ ]:
def create_first_five_integer_dataframe() -> pd.core.frame.DataFrame:
    """
    >>> first_five_integer_dataframe = create_first_five_integer_dataframe()
    >>> first_five_integer_dataframe
         even  odd  prime
    1st     0    1      2
    2nd     2    3      3
    3rd     4    5      5
    4th     6    7      7
    5th     8    9     11
    >>> type(first_five_integer_dataframe)
    pandas.core.frame.DataFrame
    """
    ### BEGIN SOLUTION

    ### END SOLUTION

## 07. 由 Christopher Nolan、Steven Spielberg 執導的電影

定義函數 `filter_christopher_nolans_steven_spielbergs_movies()` 將 `movies.csv` 中由 Christopher Nolan、Steven Spielberg 執導的電影篩選出來。先執行下方儲存格將 `movies.csv` 下載至工作目錄。

In [ ]:
!wget -Nq https://raw.githubusercontent.com/datainpoint/classroom-fintech-bot-2026/refs/heads/main/movies.csv

In [ ]:
def filter_christopher_nolans_steven_spielbergs_movies() -> pd.core.frame.DataFrame:
    """
    >>> christopher_nolans_steven_spielbergs_movies = filter_christopher_nolans_steven_spielbergs_movies()
    >>> type(christopher_nolans_steven_spielbergs_movies)
    pandas.core.frame.DataFrame
    >>> christopher_nolans_steven_spielbergs_movies
          id                                          title  release_year  rating  \
    3      4                                The Dark Knight          2008     9.0
    5      6                               Schindler's List          1993     8.9
    12    13                                      Inception          2010     8.8
    25    26                            Saving Private Ryan          1998     8.6
    28    29                                   Interstellar          2014     8.6
    46    47                                   The Prestige          2006     8.5
    53    54                                        Memento          2000     8.4
    55    56  Indiana Jones and the Raiders of the Lost Ark          1981     8.4
    70    71                          The Dark Knight Rises          2012     8.4
    121  122             Indiana Jones and the Last Crusade          1989     8.2
    126  127                                  Batman Begins          2005     8.2
    163  164                                  Jurassic Park          1993     8.1
    188  189                            Catch Me If You Can          2002     8.1

                  director  runtime
    3    Christopher Nolan      152
    5     Steven Spielberg      195
    12   Christopher Nolan      148
    25    Steven Spielberg      169
    28   Christopher Nolan      169
    46   Christopher Nolan      130
    53   Christopher Nolan      113
    55    Steven Spielberg      115
    70   Christopher Nolan      164
    121   Steven Spielberg      127
    126  Christopher Nolan      140
    163   Steven Spielberg      127
    188   Steven Spielberg      141
    """
    ### BEGIN SOLUTION

    ### END SOLUTION

## 08. 每年有幾部電影

定義函數 `count_movies_by_years()` 將 `movies.csv` 中 250 部電影依照上映年份分組後計數。

In [ ]:
def count_movies_by_years() -> pd.core.series.Series:
    """
    >>> movies_by_years = count_movies_by_years()
    >>> type(movies_by_years)
    pandas.core.series.Series
    >>> movies_by_years
    release_year
    1921    1
    1924    1
    1925    1
    1926    1
    1927    1
           ..
    2017    3
    2018    6
    2019    8
    2020    2
    2021    1
    Name: title, Length: 85, dtype: int64
    """
    ### BEGIN SOLUTION

    ### END SOLUTION

## 09. 大於等於五部電影的導演

定義函數 `count_movies_by_directors()` 將 `movies.csv` 中 250 部電影依照導演分組後計數，並將計數大於等於 5 的篩選出來、以電影數遞減排序。

In [ ]:
def count_movies_by_directors() -> pd.core.series.Series:
    """
    >>> movies_by_directors = count_movies_by_directors()
    >>> type(movies_by_directors)
    pandas.core.series.Series
    >>> movies_by_directors
    director
    Christopher Nolan    7
    Martin Scorsese      7
    Stanley Kubrick      7
    Akira Kurosawa       6
    Alfred Hitchcock     6
    Steven Spielberg     6
    Billy Wilder         5
    Charles Chaplin      5
    Hayao Miyazaki       5
    Quentin Tarantino    5
    Name: title, dtype: int64
    """
    ### BEGIN SOLUTION

    ### END SOLUTION

## 10.  以小時、分鐘表示電影長度

定義函數 `calculate_movie_hours_and_minutes()` 將 `movies.csv` 的 `runtime` 衍生計算為兩個欄位 `runtime_hours`、`runtime_minutes`

In [ ]:
def calculate_movie_hours_and_minutes() -> pd.core.frame.DataFrame:
    """
    >>> movie_hours_and_minutes = calculate_movie_hours_and_minutes()
    >>> type(movie_hours_and_minutes)
    pandas.core.frame.DataFrame
    >>> movie_hours_and_minutes
                                                  title  runtime_hours  \
    0                          The Shawshank Redemption              2
    1                                     The Godfather              2
    2                            The Godfather: Part II              3
    3                                   The Dark Knight              2
    4                                      12 Angry Men              1
    ..                                              ...            ...
    245  Neon Genesis Evangelion: The End of Evangelion              1
    246                              7 Kogustaki Mucize              2
    247                                      Tangerines              1
    248                                        Drishyam              2
    249                                          Swades              3

         runtime_minutes
    0                 22
    1                 55
    2                 22
    3                 32
    4                 36
    ..               ...
    245               27
    246               12
    247               27
    248               43
    249                9

    [250 rows x 3 columns]
    """
    ### BEGIN SOLUTION

    ### END SOLUTION

## 練習題到此結束

In [ ]:
import unittest

def run_suite(test_class):
    suite = unittest.TestLoader().loadTestsFromTestCase(test_class)
    runner = unittest.TextTestRunner(verbosity=2)
    test_results = runner.run(suite)
    number_of_failures = len(test_results.failures)
    number_of_errors = len(test_results.errors)
    number_of_test_runs = test_results.testsRun
    number_of_successes = number_of_test_runs - (number_of_failures + number_of_errors)
    chapter_percentage = number_of_successes * 100 / number_of_test_runs
    print("你的練習題完成率為 ... {:.2f}% ({}/{})".format(chapter_percentage, number_of_successes, number_of_test_runs))

class TestDayFour(unittest.TestCase):
    def test_01(self):
        self.assertEqual(answer_01, 5)
    def test_02(self):
        self.assertEqual(answer_02, 4)
    def test_03_create_first_ten_primes_array(self):
        first_ten_primes_array = create_first_ten_primes_array()
        np.testing.assert_equal(first_ten_primes_array, np.array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29]))
        self.assertIsInstance(first_ten_primes_array, np.ndarray)
        self.assertEqual(first_ten_primes_array.shape, (10,))
    def test_04_create_first_ten_evens_array(self):
        first_ten_evens_array = create_first_ten_evens_array()
        np.testing.assert_array_equal(first_ten_evens_array,
                                     np.array([0,  2,  4,  6,  8, 10, 12, 14, 16, 18]))
        self.assertIsInstance(first_ten_evens_array, np.ndarray)
        self.assertEqual(first_ten_evens_array.shape, (10,))
    def test_05_convert_kilometers_to_miles(self):
        result_array = convert_kilometers_to_miles(np.array([1.6, 3, 5, 10, 21.095, 42.195]))
        self.assertTrue(result_array[0] >= 0.9)
        self.assertTrue(result_array[1] >= 1.8)
        self.assertTrue(result_array[2] >= 3)
        self.assertTrue(result_array[3] >= 6)
        self.assertTrue(result_array[4] >= 13)
        self.assertTrue(result_array[5] >= 26)
    def test_06_create_first_five_integer_dataframe(self):
        first_five_integer_dataframe = create_first_five_integer_dataframe()
        pd.testing.assert_index_equal(first_five_integer_dataframe.index, pd.Index(['1st', '2nd', '3rd', '4th', '5th']))
        self.assertEqual(first_five_integer_dataframe.shape, (5, 3))
    def test_07_filter_christopher_nolans_steven_spielbergs_movies(self):
        christopher_nolans_steven_spielbergs_movies = filter_christopher_nolans_steven_spielbergs_movies()
        self.assertEqual(christopher_nolans_steven_spielbergs_movies.shape, (13, 6))
    def test_08_count_movies_by_years(self):
        movies_by_years = count_movies_by_years()
        self.assertEqual(movies_by_years.shape, (85,))
    def test_09_count_movies_by_directors(self):
        movies_by_directors = count_movies_by_directors()
        self.assertEqual(movies_by_directors.shape, (10,))
    def test_10_calculate_movie_hours_and_minutes(self):
        movie_hours_and_minutes = calculate_movie_hours_and_minutes()
        self.assertEqual(movie_hours_and_minutes.shape, (250, 3))

run_suite(TestDayFour)