<a href="https://colab.research.google.com/github/leeet1004835/colab/blob/main/05_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 臺灣銀行委辦 AI 人才進階訓練

> 隨堂練習：機器學習（一），2026-04-23

[郭耀仁](https://hahow.in/@tonykuoyj?tr=tonykuoyj) | <yaojenkuo@ntu.edu.tw>

## 練習題指引

- 單選題：覺得第一個選項正確，就將 `None` 改寫為 1，覺得第二個選項正確，就將 `None` 改寫為 2，覺得第三個選項正確，就將 `None` 改寫 3，覺得第四個選項正確，就將 `None` 改寫 4
- 練習題已經給定函數、類別、預期輸入或參數名稱，我們只需要寫作程式區塊。同時也給定函數的類別提示，說明預期輸入以及預期輸出的類別。
- 說明（Docstring）會描述測試如何進行，閱讀說明能夠暸解預期輸入以及預期輸出之間的關係，幫助我們更快解題。
- 請在 `### BEGIN SOLUTION` 與 `### END SOLUTION` 這兩個註解之間寫作函數或者類別的程式區塊。
- 將預期輸出放置在 `return` 保留字之後，若只是用 `print()` 函數將預期輸出印出無法通過測試。
- 語法錯誤（`SyntaxError`）或縮排錯誤（`IndentationError`）等將會導致測試失效，測試之前應該先在筆記本使用函數觀察是否與說明（Docstring）描述的功能相符。
- 執行測試的步驟：
    1. 點選右上角 Connect
    2. 點選上方選單的 Runtime -> Restart and run all -> Yes -> Run anyway
    3. 移動到 Google Colab 的最後一個儲存格看批改測試結果。

## 01. 下列有關 Tom Mitchell 對機器學習的定義，何者有誤？

1. 三要素中的 E 指的是 Experience
2. 三要素中的 T 指的是 Training
3. 三要素中的 P 指的是 Performance measure
4. 一但書指的是 If its P at T improves with E

In [ ]:
answer_01 = 2

## 02. 在機器學習的資料表達中，目標陣列（Target array）的外型、維度分別為何？

1. `m` 零維。
2. `(m,)` 一維。
3. `(m, 1)` 二維。
4. 以上皆非。

In [ ]:
answer_02 = 2

## 03. 在機器學習的資料表達中，特徵矩陣（Feature matrix）的外型、維度分別為何？

1. `m` 零維。
2. `(m,)` 一維。
3. `(n,)` 一維。
4. `(m, n)` 二維。
5. 以上皆非。

In [ ]:
answer_03 = 4

## 04. 有關 Python 機器學習的模組 Scikit-Learn 中，下列何者不是它的特色與設計原則？

1. 一致性。
2. 可檢查性。
3. 不擴增新類別。
4. 可組合性。
5. 超參數無預設值，必須由使用者決定。

In [ ]:
answer_04 = 5

## 05. 添加截距與二次項

定義函數 `create_polynomial_features_for_ndarray()` 能夠將輸入的 `ndarray` 添加截距與二次項後回傳。

In [43]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np

def create_polynomial_features_for_ndarray(X):
    """
    >>> input_ndarray = np.arange(10).reshape(-1, 1)
    >>> input_ndarray
    array([[0],
           [1],
           [2],
           [3],
           [4],
           [5],
           [6],
           [7],
           [8],
           [9]])
    >>> create_polynomial_features_for_ndarray(input_ndarray)
    array([[ 1.,  0.,  0.],
           [ 1.,  1.,  1.],
           [ 1.,  2.,  4.],
           [ 1.,  3.,  9.],
           [ 1.,  4., 16.],
           [ 1.,  5., 25.],
           [ 1.,  6., 36.],
           [ 1.,  7., 49.],
           [ 1.,  8., 64.],
           [ 1.,  9., 81.]])
    """
    ### BEGIN SOLUTION
    polynomial_features = PolynomialFeatures()
    X_transformed = polynomial_features.fit_transform(X)
    return X_transformed
    ### END SOLUTION

In [44]:
input_ndarray = np.arange(10).reshape(-1, 1)
input_ndarray

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [45]:
create_polynomial_features_for_ndarray(input_ndarray)

array([[ 1.,  0.,  0.],
       [ 1.,  1.,  1.],
       [ 1.,  2.,  4.],
       [ 1.,  3.,  9.],
       [ 1.,  4., 16.],
       [ 1.,  5., 25.],
       [ 1.,  6., 36.],
       [ 1.,  7., 49.],
       [ 1.,  8., 64.],
       [ 1.,  9., 81.]])

## 06. z-score 標準化

定義函數 `standardize_a_ndarray()` 能夠將輸入的 `ndarray` 進行 z-score 標準化後回傳。

\begin{equation}
z = \frac{X - \mu}{\sigma}
\end{equation}

In [50]:
from sklearn.preprocessing import StandardScaler

def standardize_a_ndarray(X):
    """
    >>> input_ndarray = np.arange(10).reshape(-1, 1)
    >>> input_ndarray
    array([[0],
           [1],
           [2],
           [3],
           [4],
           [5],
           [6],
           [7],
           [8],
           [9]])
    >>> standardize_a_ndarray(input_ndarray)
    array([[-1.5666989 ],
           [-1.21854359],
           [-0.87038828],
           [-0.52223297],
           [-0.17407766],
           [ 0.17407766],
           [ 0.52223297],
           [ 0.87038828],
           [ 1.21854359],
           [ 1.5666989 ]])
    """
    ### BEGIN SOLUTION
    standard_scaler = StandardScaler()
    X_transformed = standard_scaler.fit_transform(X)
    return X_transformed
    ### END SOLUTION

In [51]:
input_ndarray = np.arange(10).reshape(-1, 1)
input_ndarray

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [53]:
standardize_a_ndarray(input_ndarray)

array([[-1.5666989 ],
       [-1.21854359],
       [-0.87038828],
       [-0.52223297],
       [-0.17407766],
       [ 0.17407766],
       [ 0.52223297],
       [ 0.87038828],
       [ 1.21854359],
       [ 1.5666989 ]])

## 07. 最小最大標準化

定義函數 `min_max_a_ndarray()` 能夠將輸入的 `ndarray` 進行最小最大標準化後回傳。

```
X_std = (X - X.min(axis=0)) / (X.max(axis=0) - X.min(axis=0))
X_scaled = X_std * (max - min) + min
```

In [54]:
from sklearn.preprocessing import MinMaxScaler

def min_max_a_ndarray(X):
    """
    >>> input_ndarray = np.arange(10).reshape(-1, 1)
    >>> input_ndarray
    array([[0],
           [1],
           [2],
           [3],
           [4],
           [5],
           [6],
           [7],
           [8],
           [9]])
    >>> min_max_a_ndarray(input_ndarray)
    array([[0.        ],
           [0.11111111],
           [0.22222222],
           [0.33333333],
           [0.44444444],
           [0.55555556],
           [0.66666667],
           [0.77777778],
           [0.88888889],
           [1.        ]])
    """
    ### BEGIN SOLUTION
    min_max_scaler = MinMaxScaler()
    X_transformed = min_max_scaler.fit_transform(X)
    return X_transformed
    ### END SOLUTION

In [55]:
input_ndarray = np.arange(10).reshape(-1, 1)
input_ndarray

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [56]:
min_max_a_ndarray(input_ndarray)

array([[0.        ],
       [0.11111111],
       [0.22222222],
       [0.33333333],
       [0.44444444],
       [0.55555556],
       [0.66666667],
       [0.77777778],
       [0.88888889],
       [1.        ]])

## 08. 載入 `regression_5566_train.csv`

定義函數 `import_regression()` 將工作目錄的 `regression_5566_train.csv` 載入。

In [25]:
!wget -Nq https://raw.githubusercontent.com/datainpoint/classroom-fintech-bot-2026/refs/heads/main/regression_5566_train.csv

In [29]:
import pandas as pd

def import_regression():
    """
    >>> train = import_regression()
    >>> type(train)
    pandas.core.frame.DataFrame
    >>> train.shape
    (15, 2)
    """
    ### BEGIN SOLUTION
    train = pd.read_csv('regression_5566_train.csv')
    return train
    ### END SOLUTION

In [32]:
train = import_regression()
type(train)
print(train.shape)

pandas.core.frame.DataFrame

## 09. 擷取目標陣列與特徵矩陣

定義函數 `extract_target_array_feature_matrix_regression()` 以 `regression_5566_train.csv` 中的 `y` 作為目標陣列 $y$、`x1` 作為特徵矩陣 $X$

In [37]:
def extract_target_array_feature_matrix_regression() -> tuple:
    """
    >>> y, X = extract_target_array_feature_matrix_regression()
    >>> type(y)
    numpy.ndarray
    >>> type(X)
    numpy.ndarray
    >>> y.shape
    (15,)
    >>> X.shape
    (15, 1)
    """
    ### BEGIN SOLUTION
    y, X = train['y'].values, train['x1'].values
    return y, X
    ### END SOLUTION

In [38]:
y, X = extract_target_array_feature_matrix_regression()
print(type(y))
print(type(X))
print(y.shape)
print(X.shape)

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
(15,)
(15,)


## 10. 使用正規方程找出規則 $w$

定義函數 `find_w_with_normal_equation_regression()` 找出目標陣列 $y$、特徵矩陣 $X$ 之間的規則 $w$

In [40]:
def find_w_with_normal_equation_regression(X, y) -> tuple:
    """
    >>> y, X = extract_target_array_feature_matrix_regression()
    >>> w0, w1 = find_w_with_normal_equation_regression(X, y)
    >>> w0
    55.0
    >>> w1
    65.99999999999997
    """
    ### BEGIN SOLUTION
    y, X = extract_target_array_feature_matrix_regression()
    X = np.array(X).reshape(-1, 1)
    y = np.array(y).reshape(-1, 1)
    X = np.concatenate((np.ones((X.shape[0], 1)), X), axis=1)
    w = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
    return w[0][0], w[1][0]
    ### END SOLUTION

In [42]:
y, X = extract_target_array_feature_matrix_regression()
w0, w1 = find_w_with_normal_equation_regression(X, y)
print(w0)
print(w1)

54.999999999999886
66.0


## 練習題到此結束

In [ ]:
import unittest
import numpy as np

def run_suite(test_class):
    suite = unittest.TestLoader().loadTestsFromTestCase(test_class)
    runner = unittest.TextTestRunner(verbosity=2)
    test_results = runner.run(suite)
    number_of_failures = len(test_results.failures)
    number_of_errors = len(test_results.errors)
    number_of_test_runs = test_results.testsRun
    number_of_successes = number_of_test_runs - (number_of_failures + number_of_errors)
    chapter_percentage = number_of_successes * 100 / number_of_test_runs
    print("你的練習題完成率為 ... {:.2f}% ({}/{})".format(chapter_percentage, number_of_successes, number_of_test_runs))

class TestDayFive(unittest.TestCase):
    def test_01(self):
        self.assertEqual(answer_01, 2)
    def test_02(self):
        self.assertEqual(answer_02, 2)
    def test_03(self):
        self.assertEqual(answer_03, 4)
    def test_04(self):
        self.assertEqual(answer_04, 5)
    def test_05_create_polynomial_features_for_ndarray(self):
        input_ndarray = np.arange(10).reshape(-1, 1)
        self.assertEqual(create_polynomial_features_for_ndarray(input_ndarray).shape, (10, 3))
    def test_06_standardize_a_ndarray(self):
        input_ndarray = np.arange(10).reshape(-1, 1)
        self.assertEqual(standardize_a_ndarray(input_ndarray).shape, (10, 1))
    def test_07_min_max_a_ndarray(self):
        input_ndarray = np.arange(10).reshape(-1, 1)
        self.assertEqual(min_max_a_ndarray(input_ndarray).shape, (10, 1))
    def test_08_import_regression(self):
        train = import_regression()
        self.assertIsInstance(train, pd.core.frame.DataFrame)
        self.assertEqual(train.shape, (15, 2))
    def test_09_extract_target_array_feature_matrix_regression(self):
        y, X = extract_target_array_feature_matrix_regression()
        self.assertEqual(y.shape, (15,))
        self.assertEqual(X.shape, (15, 1))
    def test_10_find_w_with_normal_equation_regression(self):
        y, X = extract_target_array_feature_matrix_regression()
        w0, w1 = find_w_with_normal_equation_regression(X, y)
        self.assertTrue(w0 > 50)
        self.assertTrue(w0 < 60)
        self.assertTrue(w1 > 65)
        self.assertTrue(w1 < 70)

run_suite(TestDayFive)